# Generated by Django 5.0.7 on 2024-08-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_ticket_author_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, help_text='Description du livre', max_length=2048),
        ),
    ]
