# Generated by Django 5.0.7 on 2024-08-25 23:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Description du livre', max_length=2048),
        ),
    ]
